### ISSUE TITLE
Plugin doesn't work on minecraft version 1.8.9

### ISSUE THREAD

**Issue by GershonR** [thomas15v/NoXray#1]
http://pastebin.com/nFqxxNYt

**Comment by thomas15v** [comment]
Need some more information sir.

Like: Minecraft Version, SpongeForge version, Mods installed, The complete log.

But by the looks of it, it looks like the refmap isn't applied what is really odd. My biggest guess is that you are using a minecraft version lower than 1.10.2. The technology I am using doesn't exist in the older versions of sponge (although I might can get it to work on older version of spongeforge).

**Comment by GershonR** [comment]
Details:
    Minecraft Version: 1.8.9
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_92, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3987734504 bytes (3802 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
    JVM Flags: 4 total; -Xmx6144M -Xms6144M -XX:+UseG1GC -Xss2M
    IntCache: cache: 0, tcache: 0, allocated: 17, tallocated: 89
    FML: MCP 9.19 Powered by Forge 11.15.1.1890 34 mods loaded, 34 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](custom.jar) 
    UCHIJAAAA   Forge{11.15.1.1890} [Minecraft Forge](custom.jar) 
    UCHIJAAA    sponge{1.8.9-1890-4.2.0-BETA-1547} [SpongeForge](spongeforge-1.8.9-1890-4.2.0-BETA-1547.jar) 
    UCHIJAAA    noxray{0.1} [NoXray](NoXray.jar) 
    UCHIJAAA    com.github.games647.actionbroadcaster{0.4.2} [ActionBroadcaster](ActionBroadcaster.jar) 
    UCHIJAAA    io.github.hsyyid.adminshop{1.8} [AdminShop](AdminShop-1.8.jar) 
    UCHIJAAA    changeskin{1.7} [ChangeSkin](ChangeSkin.jar) 
    UCHIJAAA    de.yottaflops.easyscoreboard{1.1} [Easy Scoreboards](EasyScoreboards.jar) 
    UCHIJAAA    io.github.flibio.economylite{2.1.0} [EconomyLite](EconomyLite-v2.1.0.jar) 
    UCHIJAAA    io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds](EssentialCmds-1.8.9-8.1.11-universal.jar) 
    UCHIJAAA    pixelmon{4.2.7} [Pixelmon](Pixelmon-1.8.9-4.2.7-universal.jar) 
    UCHIJAAA    ivsevs{4.1.0} [IVsEVs](Evs-Ivs-1.8.9-4.1.0-universal.jar) 
    UCHIJAAA    Explosion Guard{Beta.1.0} [ExplosionGuard](ExplosionGuard2-0.0.4.jar) 
    UCHIJAAA    flexiblelogin{0.8} [FlexibleLogin](FlexibleLogin %283%29.jar) 
    UCHIJAAA    gameshark{4.1.0} [Gameshark (Pixelmon)](Gameshark-1.8.9-4.1.0-universal.jar) 
    UCHIJAAA    de.randombyte.holograms{v1.0.1} [Holograms](holograms-v1.0.1.jar) 
    UCHIJAAA    keys{1.2} [keys](Keys-1.2.1-1-g46a0267.jar) 
    UCHIJAAA    io.github.hsyyid.kits{1.7.4} [Kits](Kits-1.7.4.jar) 
    UCHIJAAA    minecraftmarket{2.1.0} [MinecraftMarket](minecraftmarket-plugin-2.1.0.jar) 
    UCHIJAAA    nofalldamage{1.0.0} [NoFallDamage](NoFallDamage-1.0-SNAPSHOT %281%29.jar) 
    UCHIJAAA    nuvotifier{2.3.2.2} [NuVotifier](nuvotifier-universal-2.3.2.2 %281%29.jar) 
    UCHIJAAA    ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx](PermissionsEx-Sponge.jar) 
    UCHIJAAA    pixelannouncer{1.0.0} [Pixel Announcer](PixelAnnouncer-1.8.9-1.0.0-universal.jar) 
    UCHIJAAA    pixelextras{2.1.1} [Pixel Extras](PixelExtras-1.8.9-2.1.1-universal.jar) 
    UCHIJAAA    pixelshout{1.0.1} [Pixel Shout](PixelShout-1.8.9-1.0.1-universal.jar) 
    UCHIJAAA    io.github.hsyyid.polis{2.6.6} [Polis](Polis-1.8.9-2.6.8.jar) 
    UCHIJAAA    com.gmail.trentech.pjw{0.9.1} [Project Worlds](projectworlds-4.1.0-0.9.1.jar) 
    UCHIJAAA    react{1.2.4} [React](React-1.2.4.jar) 
    UCHIJAAA    br.net.fabiozumbi12.redprotect{6.4.9} [RedProtect](RedProtect_Sponge %288%29.jar) 
    UCHIJAAA    io.github.faegy.restartnotifier{1.0.1} [Restart Notifier](RestartNotifier-v1.0.1.jar) 
    UCHIJAAA    io.github.hsyyid.votifierlistener{0.6.1} [VotifierListener](SimpleVotifierListener-0.6.1.jar) 
    UCHIJAAA    spawnofpsy{2.1.1} [SpawnOfPsyduck](SpawnOfPsyduck-1.8.9-2.1.1-universal.jar) 
    UCHIJAAA    wondertrade{4.3.1} [Wondertrade](WonderTrade-1.8.9-4.3.1-universal.jar) 

spongeforge-1.8.9-1890-4.2.0-BETA-1547.jar

**Comment by thomas15v** [comment]
Their are 2 things I can do to fix this:
- Make a hacky implementation to get it working on spongeforge 1.8.9 
- or wait until Mixins get updated in spongecommon on 1.8.9 (what I possibly will be ending up doing, because I am lazy)

As it stands now this plugin is 1.10.2 only.

**Comment by GershonR** [comment]
Ok, it's your choice since you are the developer

**Comment by inklit** [comment]
It would be very nice if this did work on 1.8.9 since it is the only Sponge anti-xray solution.
I'd take a hacky implementation over nothing.

**Comment by thomas15v** [comment]
Well at this point I am actually reprogramming and optimizing a lot of stuff (see develop branch). Once those are ready I will look in to 1.8.9.

**Comment by inklit** [comment]
Sounds good. Looking forward to it.

**Comment by thomas15v** [comment]
I don't think I am going to do this, sorry folks.

**Comment by inklit** [comment]
No problem, I've already updated to 1.10.2 in the mean time.
