### ISSUE TITLE
AntiXray not Working

### ISSUE THREAD

**Issue by Mohron** [thomas15v/NoXray#7]
Version: NoXray 0.3.2-beta.jar
Sponge: spongeforge-1.10.2-2123-6.0.0-BETA-1876.jar
Forge: forge-1.10.2-12.18.2.2122-universal.jar
Modpack: FTB Infinity Lite v1.0.1
Xray Mod: [Xray v33](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292688-xray-mod-1-6-4-1-10-vanilla-forge-liteloader)

Okay so background is I used this before on FTB's Hermitpack and it cut down the visible ores considerably and I was incredibly happy with it!  I recently set up FTB Infinity Lite and after I installed xray I found it worked perfectly as if there was no antixray plugin all together. I'm not sure if it's forge/sponge/xray or what that broke the plugin but i would really love to have it working again.

**Comment by thomas15v** [comment]
Yeah I am aware that NoXray isn't working that. But atm I don't really have much time to work on it. Not to mention that the way I realized this is causing a memory leak according bloodmc. Wich means I probably have to rethink the entire inner workings of NoXray.

**Comment by Mohron** [comment]
Did blood give you any suggestions or to fix it? Do you plan to still support the plugin when you find time? Is there anything I can do to help expedite a fix? Unfortunately the x ray mod is  basically impossible to detect as far as its presence in a client so that leave servers to track behavior or minimize the level of effectiveness. I think your plugin did a great job at the later making the xray issue small enough to not be a focus.

**Comment by thomas15v** [comment]
- He told me to do '/sponge heap' to figure out the leak.
- Sure thing.
- You could clone the repo and try to make sense of my mess xD. Basicly all this plugin does, is changing the data being send to the client without changing the inner server data (wich is a pretty hard thing to do)

**Comment by GershonR** [comment]
Is this still being developed?

**Comment by thomas15v** [comment]
Time is the problem ... . When you get home of 9 hour python programming at work, turning the computer back on to program some minecraft stuff is ehm a pretty hard thing to do XD. I possibly pick this back up when I get a holiday.

**Comment by bloodmc** [comment]
@thomas15v I decided to take a look and fix the issue for you. I'll submit a PR so you can continue work on it.

**Comment by bloodmc** [comment]
PR is here

https://github.com/thomas15v/NoXray/pull/8
