### ISSUE TITLE
More modifiers

### ISSUE THREAD

**Issue by thomas15v** [thomas15v/NoXray#9]
At this moment NoXray only hides the obvious ores. But we could of course go a bit further:

* [x] Modifier that changes stone in to random ores from the ore registry
* [ ] Modifier that changes stone in random veins.
* [ ] Modifier that adds fake blocks randomly in the map, causing very disappointed faces. 
* [ ] Modifier that hides the cave ores and calculates if the player should see those blocks (hard*)

**Comment by thomas15v** [comment]
To give some sort of update. I kinda finished the random ore generator, but I am trying to get more performence out of it (that's the reason I haven't pushed it yet).

I will push it to the develop branch when I get home.

**Comment by inklit** [comment]
Sweet! I'm excited. This is such an important feature for any server that requires a stable economy ~~it's crazy that this isn't implemented in Sponge itself.~~

**Comment by thomas15v** [comment]
I don't think its sponge its job to implement an anti-xray solution. Their are sure servers out their who don't want it, or do not have enough tick time to spare to fully utilize it.

**Comment by inklit** [comment]
True enough, but if we take Spigot for example, it's disabled by default but configurable and built into the core. 
However now that I think about it, Spigot does not provide the necessary tools required to do anti-xray and that is probably why it's built in.
Sponge on the other hand does provide the necessary tools so I suppose there is no reason to build it in.

**Comment by thomas15v** [comment]
Yeah sponge provides the correct tools, however if minecraft was about to update. This (mixin-)plugin will break. Since mixins aren't uniform across minecraft versions. Although I already have an idea to maintain multiple versions without to much hassle.
